Update test vectors for BBS Signature Scheme version 05
w3c/vc-di-bbs pull request #117
Opened 2024-01-10 01:27 UTC by Wind4Greg

This PR updates the test vectors based on the latest release of the draft BBS specification [draft-irtf-cfrg-bbs-signatures-05](https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-05.html#). 

Note that the proof generation/verification procedure has been updated in this version. Test vectors are **informative** but very helpful to developers. Also the text accompanying the test vectors has not changed only the computed values.

2024-01-10 01:36 UTC, dlongley approved these changes
+1 to getting these in. Thanks!

2024-01-17 01:26 UTC, Wind4Greg commented
Folks, these test vectors have been updated to include the changes requested in issues: https://github.com/w3c/vc-di-bbs/issues/118, https://github.com/w3c/vc-di-bbs/issues/122, https://github.com/w3c/vc-di-bbs/issues/125, and https://github.com/w3c/vc-di-bbs/issues/126.

These changes are implemented in PRs: https://github.com/w3c/vc-di-bbs/pull/128, https://github.com/w3c/vc-di-bbs/pull/129, and https://github.com/w3c/vc-di-bbs/pull/131.

@TallTed there is some new text at the beginning of section A.2 Derived Proof. Other than that all the changes are in the test vector data.

For those interest the code for generating the test vectors can be found in https://github.com/Wind4Greg/ECDSA-SD-TestVectors/tree/main/BBS.

2024-01-17 17:03 UTC, dlongley approved these changes
I'll be trying these against DB's implementation when I get a chance. Thanks!

2024-01-18 00:49 UTC, dlongley commented
I checked some of these test vectors successfully against DB's implementation. The only hang up was with the CBOR serialization of byte strings and I've filed an issue related to that: #134. We can merge these as-is and update after that issue is resolved or wait for it -- I'm ok either way.

2024-01-19 00:43 UTC, TallTed requested changes

2024-01-19 00:43 UTC, TallTed commented on index.html
> +following `seed` and `presentationHeader` values in hex are given below.
```suggestion
Random numbers are used, and an optional `presentationHeader` can be an input,
for the creation of <q>BBS proofs</q>. To furnish a deterministic set of test
vectors, we used the <q>Mocked Random Scalars</q> procedure from
[[CFRG-BBS-SIGNATURE]]. The `seed` and `presentationHeader` values we used for
generation of the derived proof test vectors are given in hex, below.
```

2024-01-25 22:39 UTC, TallTed approved these changes

2024-02-01 17:47 UTC, Wind4Greg commented
Folks (@dlongley, @TallTed ), the base example credential was missing the required `issuer` property. I updated the examples to make sure all credentials produced include this required property.

2024-02-02 16:45 UTC, msporny approved these changes

2024-02-05 17:00 UTC, Wind4Greg commented
Informative, multiple reviews, changes requested and made, no objections, merging.

2024-02-05 17:00 UTC, merged