Update all text to specify the SHA-256 hash  function rather than SHAKE-256
w3c/vc-di-bbs pull request #128
Opened 2024-01-12 22:58 UTC by Wind4Greg

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/118 on switching to using the SHA-256 variant of BBS, using SHA-256 for hashes, and using SHA-256 for HMAC computations.

This PR does not update the test vectors. They will be updated in a separate PR.

2024-01-13 18:10 UTC, dlongley approved these changes

2024-02-02 16:46 UTC, msporny approved these changes

2024-02-02 18:57 UTC, TallTed requested changes

2024-02-02 18:57 UTC, TallTed commented on index.html
> +<var>groups.mandatory.matching</var> and utilizing the SHA-256 algorithm.
```suggestion
<var>groups.mandatory.matching</var> and using the SHA-256 algorithm.
```

2024-02-02 18:57 UTC, TallTed commented on index.html
> +<var>transformedDocument</var>.`mandatory` and utilizing the SHA-256
```suggestion
<var>transformedDocument</var>.`mandatory` and using the SHA-256
```

2024-02-05 21:06 UTC, TallTed commented
Probably better to resolve merge conflicts before I re-review

2024-02-09 17:36 UTC, msporny commented
> Probably better to resolve merge conflicts before I re-review

Ready for you to re-review @TallTed

2024-02-09 18:24 UTC, TallTed approved these changes

2024-02-09 18:58 UTC, Wind4Greg commented
Normative multiple reviews, no changes requested, no objections, merging.

2024-02-09 18:59 UTC, merged