Update algorithms to align with new cryptosuite interface
w3c/vc-di-bbs pull request #144
Opened 2024-03-05 00:34 UTC by msporny

This PR aligns the specification with the new cryptosuite interface introduced by PR w3c/vc-data-integrity#244.

2024-03-05 16:12 UTC, Wind4Greg approved these changes
Looks good!

2024-03-13 16:11 UTC, dlongley approved these changes

2024-03-13 19:03 UTC, TallTed requested changes

2024-03-13 19:03 UTC, TallTed commented on index.html
> +<a>secured data document</a> ([=map=] |securedDocument|). This algorithm returns
```suggestion
an <a>secured data document</a>. Required inputs are a
<a>secured data document</a> ([=map=] |securedDocument|). This algorithm returns
```

2024-03-13 19:03 UTC, TallTed commented on index.html
>  `presentationHeader` and `nonMandatory` to the values associated with their
```suggestion
`presentationHeader`, and `nonMandatory` to the values associated with their
```

2024-03-14 19:51 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-03-14 19:52 UTC, merged