Removed unused variable, Correct function reference.
w3c/vc-di-bbs pull request #165
Opened 2024-05-08 16:47 UTC by Wind4Greg

This PR addresses issues https://github.com/w3c/vc-di-bbs/issues/164 and https://github.com/w3c/vc-di-bbs/issues/163. It removes the unused variable *proofConfig* from the *Verify Derived Proof (bbs-2023)* procedure and updates and corrects references to the *createShuffledIdLabelMapFunction* function that is used and a "label map" in the *createDisclosureData* and *createVerifyData* procedures.

2024-05-12 15:24 UTC, dlongley approved these changes

2024-05-13 17:06 UTC, TallTed requested changes

2024-06-04 19:04 UTC, TallTed approved these changes

2024-06-14 14:55 UTC, msporny approved these changes

2024-06-14 14:58 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-06-14 14:58 UTC, merged