Fix variable reference to "selectedIndexes". Add information on public key.
w3c/vc-di-bbs pull request #167
Opened 2024-05-30 19:02 UTC by Wind4Greg

This editorial PR addresses issue https://github.com/w3c/vc-di-bbs/issues/166 by fixing the name of the variable used and adding information on how to obtain information on the public key used in the signature.

2024-05-30 22:00 UTC, dlongley requested changes

2024-05-31 18:08 UTC, Wind4Greg commented on index.html
> +`presentationHeader`, and `disclosed_indexes` set as `selectedIndexes`.
Variable naming issue `selectedIndexes` use three times, `selectiveIndexes` used 25 times. Will make consistent. Good catch.

2024-05-31 18:15 UTC, dlongley approved these changes

2024-06-04 19:07 UTC, TallTed approved these changes

2024-06-04 19:09 UTC, TallTed approved these changes

2024-06-17 16:46 UTC, msporny approved these changes

2024-06-17 16:47 UTC, msporny commented
Debatably normative, multiple reviews, changes requested and made, no objections, merging.

2024-06-17 16:47 UTC, merged