Fix missing input in Base Proof Configuration procedure.
w3c/vc-di-bbs pull request #193
Opened 2024-11-12 19:18 UTC by Wind4Greg

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/189. The input is used in the procedure but not mentioned at the beginning of the procedure with the other inputs.

***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/193.html" title="Last updated on Nov 12, 2024, 7:18 PM UTC (ab33668)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/193/ad66d38...Wind4Greg:ab33668.html" title="Last updated on Nov 12, 2024, 7:18 PM UTC (ab33668)">Diff</a>

2024-11-12 21:05 UTC, dlongley approved these changes

2024-11-12 22:10 UTC, TallTed approved these changes

2024-11-13 05:48 UTC, brianorwhatever approved these changes

2025-02-18 20:59 UTC, msporny approved these changes

2025-02-18 21:20 UTC, merged

2025-03-01 18:52 UTC, whalevietnamese requested changes

2025-03-01 18:52 UTC, whalevietnamese commented on index.html
Okii